In [1]:
import numpy as np

x = np.array([1,2,3])

print(x)
# creating vectors

[1 2 3]


In [2]:
A = np.array([
    [1,2],
    [3,4]
])

print(A)
# creating matrix

[[1 2]
 [3 4]]


In [4]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

A + B
# matrix addition

array([[ 6,  8],
       [10, 12]])

In [6]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

A @ B
# matrix multiplication

array([[19, 22],
       [43, 50]])

In [7]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

np.matmul(A,B)
# another way to multiplication

array([[19, 22],
       [43, 50]])

In [8]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

np.eye(3)
# identify matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A = np.array([
    [1,2],
    [3,4]])

A. T
# matrix tranpose

array([[1, 3],
       [2, 4]])

In [10]:
A = np.array([
    [1,2],
    [3,4]])

np.linalg.inv(A)
# matrix inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
A = np.array([
    [2,1],
    [1,3]
])

b = np.array([5,7])

x = np.linalg.solve(A,b)

print(x)
# solving XA = B 

[1.6 1.8]
