# Introduction to Scikit-learn

## Learning Objectives

In this notebook, I will learn:

- What Scikit-learn is
- Why Scikit-learn is used
- The Scikit-learn ecosystem
- The Estimator API
- The Transformer API
- The Predictor API
- The difference between fit(), transform(), fit_transform(), and predict()
- How Scikit-learn models follow a consistent API

In [1]:
import sklearn
sklearn.__version__

'1.6.1'

In [2]:
import numpy as np

X = np.array([
    [1],
    [2],
    [3],
    [4],
    [5]
])

y = np.array([
    2,
    4,
    6,
    8,
    10
])

# Our relationship is basically:
- ## y = 2x

In [4]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X,y)

LinearRegression()

The model learns the relationship between X and y

In [5]:
X_new = np.array([
    [6],
    [7],
    [8]
])

predictions = model.predict(X_new)
predictions

array([12., 14., 16.])

OMG! I am just trained a ML model 

# Practice 1:

  X = hours studied

  y = exam score

  Use:
     - X = [[1], [2], [3], [4], [5]]
and:
     -  y = [50, 55, 65, 70, 80]

   ## Task 1
       Create a Linear Regression model

   ## Task 2 
       Fit the model

   ## Task 3 
       Predict the score for: 6 hours then predict scores for 7,8,9a and print the predictions       

In [11]:
from sklearn.linear_model import LinearRegression
import numpy as np

model = LinearRegression()

x = [[1], [2], [3], [4], [5]]
y = [50, 55, 65, 70, 80]

model.fit(x,y)
# to train and learn

LinearRegression()

In [16]:
x_new1 = np.array([[6]])

predictions1 = model.predict(x_new1)
predictions1

array([86.5])

In [21]:
x_new2 = np.array([[7],
                   [8],
                   [9]])

predictions2 = model.predict(x_new2)
predictions2

array([ 94. , 101.5, 109. ])

# Summary

In this notebook, I learned:

- Scikit-learn is a Python machine learning library.
- It provides tools for preprocessing, modeling, evaluation, and model selection.
- Scikit-learn uses a consistent API across many machine learning algorithms.
- Estimators use `fit()` to learn from data.
- Predictors use `predict()` to make predictions.
- Transformers use `transform()` to transform data.
- `fit_transform()` combines `fit()` and `transform()`.
- Training data is used to learn parameters.
- Learned transformations can then be applied to new data.
- Scikit-learn makes it easier to build machine learning workflows without implementing algorithms from scratch.

## Key workflow:

Data → Fit → Predict → Evaluate