# Apply Absolute Maximum Scaling

In [8]:
import numpy as np
import pandas as pd

df = pd.read_csv("SampleFile.csv")
df = df.select_dtypes(include=np.number)
df.head()

,LotArea,MSSubClass
0,8450,60
1,9600,20
2,11250,60
3,9550,70
4,14260,60


In [9]:
max_abs = np.max(np.abs(df), axis = 0)

scaled = df / max_abs

scaled.head()

,LotArea,MSSubClass
0,0.039258,0.315789
1,0.044600,0.105263
2,0.052266,0.315789
3,0.044368,0.368421
4,0.066250,0.315789


# Min-Max Scaling

In [14]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaled_data = scaler.fit_transform(df)
scaled_data

array([[0.0334198 , 0.23529412],
       [0.03879502, 0.        ],
       [0.04650728, 0.23529412],
       ...,
       [0.03618687, 0.29411765],
       [0.03934189, 0.        ],
       [0.04037019, 0.        ]])

In [15]:
scaled_named_col = pd.DataFrame(scaled_data, columns=df.columns)

scaled_named_col.head()

,LotArea,MSSubClass
0,0.033420,0.235294
1,0.038795,0.000000
2,0.046507,0.235294
3,0.038561,0.294118
4,0.060576,0.235294


# Normalization (Vector Normalization)

In [17]:
from sklearn.preprocessing import Normalizer

scaler_normalize = Normalizer()

normalized_data = scaler_normalize.fit_transform(df)
normalized_data

array([[0.99997479, 0.00710041],
       [0.99999783, 0.00208333],
       [0.99998578, 0.00533326],
       ...,
       [0.99997003, 0.00774142],
       [0.99999788, 0.00205824],
       [0.99999797, 0.00201268]])

In [18]:
normalized_data_named_col = pd.DataFrame(normalized_data, columns=df.columns)
normalized_data_named_col.head()

,LotArea,MSSubClass
0,0.999975,0.007100
1,0.999998,0.002083
2,0.999986,0.005333
3,0.999973,0.007330
4,0.999991,0.004208


# Standardization

In [19]:
from sklearn.preprocessing import StandardScaler

scaler_standardization = StandardScaler()

scaler_standardization_scaled = scaler_standardization.fit_transform(df)
scaler_standardization_scaled

array([[-0.20714171,  0.07337496],
       [-0.09188637, -0.87256276],
       [ 0.07347998,  0.07337496],
       ...,
       [-0.14781027,  0.30985939],
       [-0.08016039, -0.87256276],
       [-0.05811155, -0.87256276]])

In [21]:
scaler_standardization_scaled_named_col = pd.DataFrame(scaler_standardization_scaled, columns=df.columns)
scaler_standardization_scaled_named_col.head()

,LotArea,MSSubClass
0,-0.207142,0.073375
1,-0.091886,-0.872563
2,0.073480,0.073375
3,-0.096897,0.309859
4,0.375148,0.073375


# Robust Scaling

In [22]:
from sklearn.preprocessing import RobustScaler

scaler_RS = RobustScaler()

scaler_RS_scaled = scaler_RS.fit_transform(df)
scaler_RS_scaled

array([[-0.25407609,  0.2       ],
       [ 0.03001482, -0.6       ],
       [ 0.43762352,  0.2       ],
       ...,
       [-0.10783103,  0.4       ],
       [ 0.05891798, -0.6       ],
       [ 0.11326581, -0.6       ]])

In [23]:
scaler_RS_scaled_named_col = pd.DataFrame(scaler_RS_scaled, columns=df.columns)
scaler_RS_scaled_named_col.head()

,LotArea,MSSubClass
0,-0.254076,0.2
1,0.030015,-0.6
2,0.437624,0.2
3,0.017663,0.4
4,1.181201,0.2
