In [1]:
import numpy as np

x = np.array([1,2,3,4,5])

In [3]:
(x*2) == (x**2)

array([False,  True, False, False, False])

In [5]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [7]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74], dtype=int32)

In [8]:
[x[3],x[7],x[2]]

[np.int32(71), np.int32(86), np.int32(14)]

In [ ]:
ind = [3,7,2]
x[ind]

array([71, 86, 14], dtype=int32)

: 