# `In the name of Allah, the most Gracious, the most Merciful`

In [1]:
import numpy as np

X = np.array([[1],[2],[3],[4]])
w = np.array([2])

print("="*50)
print("DIFFERENT WAYS TO ACCESS X[1]")
print("="*50)

# Method 1: Indexing (returns 1D)
print(f"X[1]           = {X[1]}, shape: {X[1].shape}")  
# [2], shape: (1,)

# Method 2: Slicing (returns 2D)
print(f"X[1:2]         = {X[1:2]}, shape: {X[1:2].shape}")  
# [[2]], shape: (1, 1)

# Method 3: Reshape (can change shape)
print(f"X[1].reshape(1,1) = {X[1].reshape(1,1)}, shape: {X[1].reshape(1,1).shape}")  
# [[2]], shape: (1, 1)

print("\n" + "="*50)
print("DIFFERENT WAYS TO DO THE SAME CALCULATION")
print("="*50)

# Method 1: Both 1D arrays (returns scalar)
c1 = np.dot(X[1], w)
print(f"dot(X[1], w) = {c1}, shape: {c1.shape}")  
# 4, shape: ()

# Method 2: Both 2D arrays (returns 2D)
c2 = np.dot(X[1:2], w.reshape(1,1))
print(f"dot(X[1:2], w.reshape(1,1)) = {c2}, shape: {c2.shape}")  
# [[4]], shape: (1, 1)

# Method 3: Matrix multiplication (2D only)
c3 = np.matmul(X[1:2], w.reshape(1,1))
print(f"matmul(X[1:2], w.reshape(1,1)) = {c3}, shape: {c3.shape}")  
# [[4]], shape: (1, 1)

DIFFERENT WAYS TO ACCESS X[1]
X[1]           = [2], shape: (1,)
X[1:2]         = [[2]], shape: (1, 1)
X[1].reshape(1,1) = [[2]], shape: (1, 1)

DIFFERENT WAYS TO DO THE SAME CALCULATION
dot(X[1], w) = 4, shape: ()
dot(X[1:2], w.reshape(1,1)) = [[4]], shape: (1, 1)
matmul(X[1:2], w.reshape(1,1)) = [[4]], shape: (1, 1)


## Now, I will compare between for `dot function` and `for loop`:

In [2]:
def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [3]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


In [4]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")


NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


## Now, comparing the time 

In [5]:
import time 

np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 33.4215 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 3591.7568 ms 


- So, vectorization provides a large speed up in this example. This is because NumPy makes better use of available data parallelism in the underlying hardware. GPU's and modern CPU's implement Single Instruction, Multiple Data (SIMD) pipelines allowing multiple operations to be issued in parallel. This is critical in Machine Learning where the data sets are often very large.

---

# Now, Let's move to how to create matrices 

In [6]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.44236513]]


In [7]:
# or manually 
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")

a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows

print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [8]:
print("="*50)
print("DIFFERENT WAYS TO CREATE A COLUMN VECTOR")
print("="*50)

# Method 1: All in one line
a1 = np.array([[5], [4], [3]])
print(f"Method 1: {a1}")
print(f"Shape: {a1.shape}\n")

# Method 2: Multi-line (more readable)
a2 = np.array([[5],
               [4],
               [3]])
print(f"Method 2: {a2}")
print(f"Shape: {a2.shape}\n")

# Method 3: Using reshape
a3 = np.array([5, 4, 3]).reshape(3, 1)
print(f"Method 3: {a3}")
print(f"Shape: {a3.shape}\n")

# Method 4: Using reshape with -1 (auto-calculate)
a4 = np.array([5, 4, 3]).reshape(-1, 1)
print(f"Method 4: {a4}")
print(f"Shape: {a4.shape}\n")

# Method 5: Using np.newaxis
a5 = np.array([5, 4, 3])[:, np.newaxis]
print(f"Method 5: {a5}")
print(f"Shape: {a5.shape}\n")

print("="*50)
print("ALL METHODS PRODUCE THE SAME RESULT!")
print("="*50)

DIFFERENT WAYS TO CREATE A COLUMN VECTOR
Method 1: [[5]
 [4]
 [3]]
Shape: (3, 1)

Method 2: [[5]
 [4]
 [3]]
Shape: (3, 1)

Method 3: [[5]
 [4]
 [3]]
Shape: (3, 1)

Method 4: [[5]
 [4]
 [3]]
Shape: (3, 1)

Method 5: [[5]
 [4]
 [3]]
Shape: (3, 1)

ALL METHODS PRODUCE THE SAME RESULT!


In [9]:
# 1 row, multiple columns (ROW VECTOR)
row = np.array([[5, 4, 3]])  # Shape: (1, 3)
print(row)
print(row.shape)

[[5 4 3]]
(1, 3)


In [10]:
# Multiple rows, 1 column (COLUMN VECTOR)
col = np.array([[5], 
                [4], 
                [3]])  # Shape: (3, 1)
print(col)
print(col.shape)

[[5]
 [4]
 [3]]
(3, 1)


In [11]:
# X is typically a 2D array (samples, features)
X = np.array([[1, 2, 3],    # Sample 1: features [1,2,3]
              [4, 5, 6]])   # Sample 2: features [4,5,6]
# Shape: (2, 3) → 2 samples, 3 features each

# w is a column vector (features, 1) or 1D array
w = np.array([[0.5], 
              [0.5], 
              [0.5]])  # Shape: (3, 1)

# OR
w = np.array([0.5, 0.5, 0.5])  # Shape: (3,)

# Predictions: X @ w (if using column vector)
pred = np.dot(X, w)  # Shape: (2, 1) - column vector

# OR
pred = np.dot(X, w)  # Shape: (2,) - 1D array

In [12]:
# Shape: (number of samples, number of features)
X = np.array([[1.0, 2.0, 3.0],    # Sample 1: 3 features
              [4.0, 5.0, 6.0],    # Sample 2: 3 features
              [7.0, 8.0, 9.0]])   # Sample 3: 3 features
# Shape: (3, 3) → 3 samples, 3 features each

# Access sample 1:
X[0]  # Shape: (3,) - 1D array

# Access feature 1 of sample 1:
X[0, 0]  # Shape: () - scalar

np.float64(1.0)

In [13]:
# Option 1: 1D array (most common)
w = np.array([0.5, 0.5, 0.5])  # Shape: (3,)
b = 10.0  # Shape: () - scalar

# Option 2: Column vector (less common)
w_col = np.array([[0.5],
                  [0.5],
                  [0.5]])  # Shape: (3, 1)

In [14]:
# With 1D w
X = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
w = np.array([0.5, 0.5, 0.5])         # Shape: (3,)
b = 10

pred = np.dot(X, w) + b  # Shape: (2,) - 1D array
print(pred)  # [13.0, 17.5]

# With column vector w
w_col = w.reshape(-1, 1)  # Shape: (3, 1)
pred_col = np.dot(X, w_col) + b  # Shape: (2, 1) - 2D array
print(pred_col)  # [[13.0], [17.5]]

[13.  17.5]
[[13. ]
 [17.5]]


In [15]:
print("="*50)
print("DIFFERENT ARRAY SHAPES")
print("="*50)

# 1. 1D Array
a1d = np.array([1, 2, 3])
print(f"1D Array: {a1d}")
print(f"Shape: {a1d.shape}\n")

# 2. Row Vector (1 row, n columns)
row = np.array([[1, 2, 3]])
print(f"Row Vector: {row}")
print(f"Shape: {row.shape}\n")

# 3. Column Vector (n rows, 1 column)
col = np.array([[1], [2], [3]])
print(f"Column Vector: {col}")
print(f"Shape: {col.shape}\n")

# 4. Matrix (n rows, m columns)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(f"Matrix: {matrix}")
print(f"Shape: {matrix.shape}\n")

# 5. Creating from 1D to Column Vector
a = np.array([1, 2, 3])
col_from_1d = a.reshape(-1, 1)
print(f"1D to Column Vector: {col_from_1d}")
print(f"Shape: {col_from_1d.shape}\n")

# 6. Creating from 1D to Row Vector
row_from_1d = a.reshape(1, -1)
print(f"1D to Row Vector: {row_from_1d}")
print(f"Shape: {row_from_1d.shape}")

DIFFERENT ARRAY SHAPES
1D Array: [1 2 3]
Shape: (3,)

Row Vector: [[1 2 3]]
Shape: (1, 3)

Column Vector: [[1]
 [2]
 [3]]
Shape: (3, 1)

Matrix: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

1D to Column Vector: [[1]
 [2]
 [3]]
Shape: (3, 1)

1D to Row Vector: [[1 2 3]]
Shape: (1, 3)


In [16]:
# Single feature (column vector)
X = np.array([[1.0],
              [2.0],
              [3.0],
              [4.0]])  # Shape: (4, 1)
print(f"X: {X}\nShape: {X.shape}")

# Multiple features
X = np.array([[1.0, 2.0, 3.0],    # 4 samples, 3 features
              [4.0, 5.0, 6.0],
              [7.0, 8.0, 9.0],
              [10.0, 11.0, 12.0]])  # Shape: (4, 3)

X: [[1.]
 [2.]
 [3.]
 [4.]]
Shape: (4, 1)


In [17]:
# creating labels
# Labels as 1D array
y = np.array([100, 150, 200, 250])  # Shape: (4,)

# Labels as column vector
y = np.array([[100],
              [150],
              [200],
              [250]])  # Shape: (4, 1)

In [19]:
# Initializing weights
w = np.zeros((3, 1))  # 3 features, column vector
w = np.zeros(3)       # 3 features, 1D array

# With specific values
w = np.array([0.5, 0.5, 0.5])  # 1D
w = np.array([[0.5], 
              [0.5], 
              [0.5]])  # Column

---

In [20]:
#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


- `-1` means "figure it out automatically" - NumPy calculates the number of rows needed

In [21]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
