In [ ]:
# NumPy (Numerical Python)
is a Python library used for numerical computing 

It provides:
- Fast multidimensional arrays 
- Mathematical operations 
- Linear algebra tools
- Functions used in ML and Data Science

In Machine Learning:
- Data is represented as arrays 
- Images are stored as arrays of pixels 
- Model parameters are stored as matrices


In [ ]:
import numpy as np 
# np is an alias or short name for NumPy

In [ ]:
# Creating arrays
A NumPy array is a collection of elements stored in a structured way

In [4]:
import numpy as np
numbers = np.array([1,2,3,4])
numbers

array([1, 2, 3, 4])

In [ ]:
### NumPy arrays are optimized for numerical operations and are faster than Python lists for large datasets

In [13]:
import numpy as np
numbers = np.array([1,2,3,4])
numbers

array([1, 2, 3, 4])

In [ ]:
# What is the ndarray?
It means "N-dimensional array" 
---> It's the main data structure in NumPy

In [7]:
# 1D Arrays
A one-dimensional array is similar to a list; it contains elements in a single row

In [10]:
import numpy as np
arr_1d = np.array([10,20,30])
type(arr_1d)

numpy.ndarray

In [ ]:
# 2D Arrays
2-dimensional arrays represent tables or matrices 
-->* They are very important in ML because datasets are usually stored as matrices 

In [12]:
import numpy as np
arr_2d = np.array([
    [1,2,3],
    [4,5,6]
])

arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# Understanding shape

import numpy as np
arr_2d = np.array([
    [1,2,3],
    [4,5,6]
])

arr_2d.shape

(2, 3)

In [ ]:
# explanation
Shape tells us the dimensions of the array 
---> (2,3) means 2 rows and 3 columns


In [16]:
# Understanding size

import numpy as np
arr_2d = np.array([
    [1,2,3],
    [4,5,6]
])

arr_2d.size

6

In [ ]:
# explanation 
Size returns the total number of elements in the array

In [ ]:
# dtype 
Like in normal Python 
tell us the type of data stored inside the array 

Examples:
- int 
- float 
- bool 

In [ ]:
## Mini Exercise 

Create a NumPy array representing the grades of 5 students

find:
- Array type
- shape 
- Number of elements 
- Data Type 

In [17]:
import numpy as np 

grades = np.array([90,85,70,65,50])

print(type(grades))
print(grades.shape)
print(grades.size)
print(grades.dtype)

<class 'numpy.ndarray'>
(5,)
5
int64


In [ ]:
### I noticed an important note 
There is a difference between type() and .dtype
- type() ----> returns array type 
- dtype ----> returns data type

In [ ]:
# #Summary
In this notebook, I learned the fundamentals of NumPy arrays:
- Creating arrays
- Understanding dimensions 
- Checking array properties 