In [ ]:
# In this notebook, I learn how to perform mathematical operations on NumPy arrays.

Topics:
- Arithmetic operations
- Universal functions (ufuncs)
- Aggregation functions
- Comparison operations

In [3]:
# Arithmetic Operations
import numpy as np
# Create arrays:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
# Addition:
a + b

array([ 6,  8, 10, 12])

In [ ]:
# Operations with Scalars
A scalar is a single number

a + 10

NumPy adds 10 to every element:
[11 12 13 14]
This is called broadcasting

In [ ]:
# Universal Functions (ufuncs)
NumPy provides built-in mathematical functions

- Square root:
np.sqrt(a)

- Power:
np.power(a, 2)

- Exponential:
np.exp(a)

In [ ]:
# Aggregation Functions
Working with all elements

Sum:
np.sum(a)

Mean:
np.mean(a)

Maximum:
np.max(a)

Minimum:
np.min(a)

Standard deviation:
np.std(a)

In [4]:
# Comparison Operations
a = np.array([1, 2, 3, 4])

a > 2

array([False, False,  True,  True])

In [ ]:
## Summary

In this notebook, I learned:
- How to perform arithmetic operations on NumPy arrays
- How NumPy applies operations element-wise
- How to use aggregation functions
- How to filter arrays using conditions