In [ ]:
# NumPy Indexing and Slicing

In this notebook, I learn how to access, modify, and extract data from NumPy arrays.

Topics:
- Indexing
- Negative indexing
- Slicing
- Modifying elements
- Fancy indexing
- Boolean indexing

In [4]:
# Indexing
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
arr[0] 
# first element

np.int64(10)

In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
arr[-1] 
# last element

np.int64(60)

In [6]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
arr[-2] 
# second element from right 

np.int64(50)

In [ ]:
# Slicing

General syntax:
arr[start:stop]

In [7]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
arr[2:5]

array([30, 40, 50])

In [ ]:
# notice that the last element not included 

In [8]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
arr[:4]
# Beginning to index 3

array([10, 20, 30, 40])

In [9]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
arr[2:]
# From index 2 to the end

array([30, 40, 50, 60])

In [10]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
arr[:]
# Copy the whole array

array([10, 20, 30, 40, 50, 60])

In [11]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
arr[::2] 
# Step size 

array([10, 30, 50])

In [12]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
arr[::-1]
# reverse the array

array([60, 50, 40, 30, 20, 10])

In [14]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
arr[0] = 100
# modifying elements
arr

array([100,  20,  30,  40,  50,  60])

In [16]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
arr[1:4] = [1, 2, 3]
# modifying multiple elements
arr

array([10,  1,  2,  3, 50, 60])

In [18]:
# Fancy Indexing
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
arr[[0, 2, 5]]
# Select specific positions

array([10, 30, 60])

In [19]:
# 2D Array Indexing
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# First row
matrix[0]

array([1, 2, 3])

In [20]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
matrix[1, 2]
# Second row, third column

np.int64(6)

In [ ]:
## Summary
In this notebook, I learned:

- Basic indexing
- Negative indexing
- Array slicing
- Step slicing
- Modifying array elements
- Fancy indexing
- Indexing in 2D arrays