In [ ]:
# NumPy Reshaping and Array Manipulation
In this notebook, I learn how to change array shapes and combine arrays

Topics:
- Shape
- Dimensions
- Reshape
- Flatten
- Ravel
- Transpose
- Concatenate
- Stack

In [1]:
import numpy as np

arr = np.arange(1, 13)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
import numpy as np

arr = np.arange(1, 13)     
arr.shape 

(12,)

In [ ]:
In the previous example, I used .shape, and it returned (12,)
This means the array has one dimension containing 12 elements
Since it is a one-dimensional array, there is no concept of rows and columns

In [5]:
import numpy as np

arr = np.arange(1, 13)
arr.ndim

1

In [ ]:
Okay, now I notice with .ndim that it returns the number of dimensions 
Another example to fully understand 

In [6]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])
arr.ndim

2

In [ ]:
Let's return to .shape 
If i want to reshape an array I will use .reshape (LoL very logic)

In [7]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])
# (2 rows, 3columns) = 6 elements 

arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

arr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [9]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
It's very enjoyable to play with arrays!

My golden rule ---> keep the size of the array (The total number of elements must stay the same)

In [ ]:
# flatten() and Ravel()
Convert a 2D array into a 1D copy

In [10]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [12]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

arr.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
What's the difference then??

flatten() returns a copy
ravel() usually returns a view, so changes may affect the original array

In [ ]:
# transpose() or .T
It reverses rows and columns 

(ya3ny el rows become columns w el columns become rows)

In [13]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
import numpy as np

arr=np.array([[1, 2],
       [3, 4],
       [5, 6]])

arr.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
If I have 2 arrays, and I wanna concatenate
I will use comma (,)

In [17]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

np.concatenate((arr1,arr2)) 

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Creating arrays from existing arrays:
---stack---
1) np.vstack (v for vertical)
If we have 2 arrays, it stacks them on top of each other  

2) np.hstack (h for horizontal)
It puts them beside each other 

In [20]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
3) np.split(old_array_name, number_of_sections) (in general)
Split the array into 2 arrays, and you can control the number of new arrays 

In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
np.split(arr,2)

[array([1, 2, 3]), array([4, 5, 6])]